// SINGLE line comment
/* 
multiline comment
*/
// variables
// let age = 25;
// age = 50;
// console.log(age);
// const firstname = 'vhinelle'
// firstname = 'vhi'
// console.log(firstname)
// let ass = false
// string interpolation
// putting a variable inside a string
//let firstname = 'vhinelle'
//let lastname = 'amakye'
//let myfullname =`my full name is ${firstname} ${lastname}`
//let myfullname = 'my full name is' + " "+ firstname + " " + lastname
//console.log(myfullname)
//decision statement
// if statement
/*let evennumber = 20;
if(evennumber == 50){
    console.log('the number is even');
}
let firstname = 'esther'
let age = 20;
if( firstname != 'esther'  age == 20){
    console.log( 'The name is not esther')
} else {
console.log('the name is esther and she is a liar')
}*/
// nested if statement  
/*let age = 25;
if(age == 18){
    console.log('motherfucker you are grown enough')

} else if (age == 20){
    console.log('start getting your shit together')
} else if(age == 22){
    console.log('nigga you are screwed')

} else{
    console.log('you are 40 and your life is over')
}
*/
// switch case
/*
let age = 20;
switch (age) {
    case 20:
    console.log('you are old as fuck')
    break;
    case 25:
    console.log('this is my fucking life')
    break;
    case 30:
    console.log('my life sucks')
    break;
    default:
    console.log('maybe i will make it')

// objects
let person = {
firstname: 'vhinelle',
lastname: 'amakye',
age: 22,
gender: 'female'
}
console.log(`${person['firstname']} ${person['lastname']}`)
*/
/*

let GPA = 45

if(GPA >= 80 && GPA <= 100){
console.log('you had A')
} else if(GPA >= 60 && GPA <= 79){
    console.log('You had B+')
}else if(GPA >= 50 && GPA <= 59){
    console.log('You had B ')
} else if(GPA >= 40 && GPA <=49){
    console.log('you had C')
} else {
    console.log('wo maame ab)ka cos you trailed')
}
 
// using switch case
let GPA = 85
switch (GPA) {
case GPA >= 80 && GPA <= 100:
console.log('you had A')
break;
case  (GPA >= 60 && GPA <= 79):
console.log('you had B+')
break;
case (GPA >= 50 && GPA <= 59):
console.log('you had C')
break;
default:
console.log('wo maame ab)ka you trailed')

}
*/
let Girl = {
    girlName : 'vhinelle',
    girlAge :  23,
    girlJob : 'unemployed'
}
console.log(Girl['girlName'])